### ISSUE TITLE
Setup Redux State Management

### ISSUE THREAD

**Issue by CeoFred** [CeoFred/bondpay-ui#10]
Using https://redux-toolkit.js.org/, create a store, setup its provider, create a slice, and include createAsyncThunk. please add a simple use case to verify it works. Don't forget to allow support for react-redux dev tools. A proper folder structure is key in getting the work done.

**Comment by yamitrvg12** [comment]
Hey [CeoFred](https://github.com/CeoFred), can you assign me this task so that I can work on it?

**Comment by Joshua-Ogbonna** [comment]
Hey @CeoFred, can I work on this task?
