### ISSUE TITLE
Did some minor changes

### ISSUE THREAD

**Issue by Dnyaneshvn** [CeoFred/bondpay-ui#16]
![Screenshot (222)](https://user-images.githubusercontent.com/78072155/193428211-9e0e276d-aeff-4d49-bf87-e6a0aafc6b65.png)

**Comment by CeoFred** [comment]
😂 cool,

**Comment by Dnyaneshvn** [comment]
thank you very much for merging my pr, this definitely gives me the confidence to begin my open-source journey!

**Comment by CeoFred** [comment]
@all-contributors please add @Dnyaneshvn for code
